Truncate Table Customers;
Insert into Customers(First_Name,Last_Name,emailID,Joining_Date) values ('Jason','Roy','jasonroy@extmail.com',SYSDATE);
Insert into Customers(First_Name,Last_Name,emailID,Joining_Date) values ('Nicolo','Thomas','nicolo78@extmail.com',TO_DATE('30-12-2022','DD--MM-YYYY'));
Insert into Customers(First_Name,Last_Name,emailID,Joining_Date) values ('Rahul','Sharma','rahul@extmail.com',TO_DATE('17-01-2023','DD-MM-YYYY'));
Insert into Customers(First_Name,Last_Name,emailID,Joining_Date) values ('Ankur','Bodha','ankur@extmail.com',TO_DATE('02-02-2023','DD-MM-YYYY'));
Insert into Customers(First_Name,Last_Name,emailID,Joining_Date) values ('Raheem','Khan','rkhan@extmail.com',TO_DATE('20-12-2022','DD-MM-YYYY'));
Insert into Customers(First_Name,Last_Name,emailID,Joining_Date) values ('Ajay','Mathur','ajaymathur@extmail.com',SYSDATE);
Insert into Customers(First_Name,Last_Name,emailID,Joining_Date) values ('Bill','Johnson','bill_j@extmail.com',TO_DATE('19-01-2023','DD_MM_YYYY'));
Insert into Customers(First_Name,Last_Name,emailID,Joining_Date) values ('Henry','Nicole','henryN@extmail.com',TO_DATE('30-11-2022','DD-MM-YYYY'));
Insert into Customers(First_Name,Last_Name,emailID,Joining_Date) values ('Jack','Crew','Jcrew@extmail.com',TO_DATE('20-01-2023','DD-MM-YYYY'));
Insert into Customers(First_Name,Last_Name,emailID,Joining_Date) values ('Santosh','Jha','santhosh@extmail.com',TO_DATE('17-12-2022','DD-MM-YYYY'));
Insert into Customers(First_Name,Last_Name,emailID,Joining_Date) values ('Anil','Rathor','anil78@extmail.com',TO_DATE('20-03-2023','DD-MM-YYYY'));
Insert into Customers(First_Name,Last_Name,emailID,Joining_Date) values ('James','Andresons','james_90@extmail.com',SYSDATE);
Insert into Customers(First_Name,Last_Name,emailID,Joining_Date) values ('Akash','Ray','akashR@extmail.com',TO_DATE('20-11-2022','DD-MM-YYYY'));
Insert into Customers(First_Name,Last_Name,emailID,Joining_Date) values ('Ravi','Teja','rabi_teja@extmail.com',SYSDATE);
Insert into Customers(First_Name,Last_Name,emailID,Joining_Date) values ('Bikram','Pandey','bikram87@extmail.com',TO_DATE('10-03-2023','DD-MM-YYYY'));
Insert into Customers(First_Name,Last_Name,emailID,Joining_Date) values ('Antony','Marshal','antony@extmail.com',TO_DATE('17-11-2022','DD-MM-YYYY'));
Insert into Customers(First_Name,Last_Name,emailID,Joining_Date) values ('A.K','Roy','a.roy@extmail.com',TO_DATE('01-01-2023','DD-MM-YYYY'));
COMMIT;
